"""Rename type column to expense_type in expenses table

Revision ID: 0d0edd438c0f
Revises: fa0de59dccd3
Create Date: 2025-09-07 17:11:21.774988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d0edd438c0f'
down_revision: Union[str, Sequence[str], None] = 'fa0de59dccd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('expense_type', sa.String(), nullable=True))
    op.drop_column('expenses', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('expenses', 'expense_type')
    # ### end Alembic commands ###
