"""Add hourly_wage to WeeklyEarnings

Revision ID: 669edd102d95
Revises: e063550adb8d
Create Date: 2026-03-01 14:11:48.634574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '669edd102d95'
down_revision: Union[str, Sequence[str], None] = 'e063550adb8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly_earnings', sa.Column('hourly_wage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weekly_earnings', 'hourly_wage')
    # ### end Alembic commands ###
