"""Initial migration

Revision ID: 7e0ed793c5fe
Revises: 
Create Date: 2025-09-07 16:19:04.191351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e0ed793c5fe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('vendor', sa.String(), nullable=True))
    op.add_column('expenses', sa.Column('type', sa.String(), nullable=True))
    op.alter_column('expenses', 'receipt_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('expenses', 'vendor_name')
    op.drop_column('expenses', 'status')
    op.drop_column('expenses', 'raw_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('raw_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('expenses', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('expenses', sa.Column('vendor_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('expenses', 'receipt_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('expenses', 'type')
    op.drop_column('expenses', 'vendor')
    # ### end Alembic commands ###
