"""add_notes_table

Revision ID: 959c93cbecc0
Revises: be9591ec5983
Create Date: 2026-06-13 12:25:18.838118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '959c93cbecc0'
down_revision: Union[str, Sequence[str], None] = 'be9591ec5983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('content', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_created_by'), 'notes', ['created_by'], unique=False)
    op.create_index(op.f('ix_notes_date'), 'notes', ['date'], unique=False)
    op.drop_index(op.f('idx_payslip_files_created_by'), table_name='payslip_files')
    op.create_index(op.f('ix_payslip_files_created_by'), 'payslip_files', ['created_by'], unique=False)
    op.drop_index(op.f('idx_trainings_created_by'), table_name='trainings')
    op.create_index(op.f('ix_trainings_created_by'), 'trainings', ['created_by'], unique=False)
    op.alter_column('users', 'is_calculator_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'employment_type',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("'employed'::character varying"))
    op.alter_column('users', 'has_payslip',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('weekly_earnings', 'employment_type',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("'employed'::character varying"))
    op.alter_column('weekly_earnings', 'guild_tax',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('weekly_earnings', 'is_manual_wage',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weekly_earnings', 'is_manual_wage',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('weekly_earnings', 'guild_tax',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('weekly_earnings', 'employment_type',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("'employed'::character varying"))
    op.alter_column('users', 'has_payslip',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'employment_type',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("'employed'::character varying"))
    op.alter_column('users', 'is_calculator_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_trainings_created_by'), table_name='trainings')
    op.create_index(op.f('idx_trainings_created_by'), 'trainings', ['created_by'], unique=False)
    op.drop_index(op.f('ix_payslip_files_created_by'), table_name='payslip_files')
    op.create_index(op.f('idx_payslip_files_created_by'), 'payslip_files', ['created_by'], unique=False)
    op.drop_index(op.f('ix_notes_date'), table_name='notes')
    op.drop_index(op.f('ix_notes_created_by'), table_name='notes')
    op.drop_table('notes')
    # ### end Alembic commands ###
