"""Add ondelete SET NULL to time_entries.hotel_id

Revision ID: be9591ec5983
Revises: 669edd102d95
Create Date: 2026-03-01 20:26:40.818079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be9591ec5983'
down_revision: Union[str, Sequence[str], None] = '669edd102d95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('time_entries_hotel_id_fkey'), 'time_entries', type_='foreignkey')
    op.create_foreign_key(None, 'time_entries', 'hotels', ['hotel_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'time_entries', type_='foreignkey')
    op.create_foreign_key(op.f('time_entries_hotel_id_fkey'), 'time_entries', 'hotels', ['hotel_id'], ['id'])
    # ### end Alembic commands ###
